### ISSUE TITLE
getMigrationsExcept should skip non-js files

### ISSUE THREAD

**Issue by AAzza** [JohanObrink/rethink-migrate#11]
If there are some strange files in migrations directory, in my case it was vim swp file, it b0rks! (Radu is really mad here).

Probably we should just filter out files not ending in .js.

**Comment by JohanObrink** [comment]
Fixed in https://github.com/JohanObrink/rethink-migrate/commit/546675b1d100ee07e88bb049ca72cb8e3a10f439
[Release 1.0.2](https://github.com/JohanObrink/rethink-migrate/tree/v1.0.2)
